In [ ]:
from sklearn.datasets import load_diabetes
import pandas as pd
data = load_diabetes()
data.data
df=pd.DataFrame(data.data,columns=data.feature_names)
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [ ]:
X = data.data
y = data.target

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=5)

In [ ]:

print(x.shape)
print(y.shape)

(442, 10)
(442,)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)
print(x.shape)
print(y.shape)

(442, 10)
(442,)

In [ ]:
df=pd.DataFrame(x)
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [ ]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [ ]:
df.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
print('x train',x_train[:5])
print('x test',x_test[:5])

x train [[-1.40760482e-01 -9.44154951e-01  8.47909543e-01  1.00611767e+00
   4.99666766e-01 -4.95707824e-01  1.59560967e+00 -8.36152526e-01
   1.05349869e+00  5.20279127e-01]
 [ 1.34704232e+00 -9.44154951e-01 -1.11841168e+00  2.22985217e+00
   6.42811738e-01  4.00279433e-01 -3.62375059e-01  4.71261191e-01
   1.17358900e+00  7.82398444e-01]
 [ 1.72461161e-01 -9.44154951e-01  1.12227995e+00 -1.45632453e-01
   1.18676263e+00  9.26184997e-01 -4.90975022e-02  4.63615496e-01
   1.12456479e+00  2.18036813e+00]
 [ 3.29071983e-01  1.05914818e+00  2.53440335e-01 -1.66368739e-03
   1.29738645e-02 -4.43766533e-01 -6.75652615e-01  6.92986324e-01
   1.52644930e+00  7.82398444e-01]
 [-1.94178493e+00 -9.44154951e-01 -2.95300472e-01 -7.93491897e-01
   2.42005818e-01  5.17147337e-01 -7.53972004e-01  6.92986324e-01
   4.36705720e-01 -2.66078823e-01]]
x test [[ 0.95551527 -0.94415495 -0.18097947 -0.3615856   2.58958335  2.59479895
   0.42081883  0.69298632  0.63983316 -0.17870572]
 [ 1.97348561 -0.94415495  0.73358854  0.43024261 -0.53097703 -0.34637661
   0.02922189 -0.83615253 -0.5055852  -0.52819814]
 [ 1.34704232  1.05914818 -0.13525107 -0.28960122  2.13151944  1.01058959
   1.20401272 -0.0715831   1.72501635 -0.44082503]
 [ 2.05179102 -0.94415495  1.05368735  1.63022227  1.12950464  0.7573758
  -1.61548528  2.91023766  2.02011169  1.21926397]
 [ 0.25076657  1.05914818 -0.47821407 -0.07364807  0.78595671  1.10148685
  -0.12741689  0.69298632 -0.1434141  -0.26607882]]

In [ ]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
pred=model.predict(x_test)
print(pred[:41])
print(type(pred))
print(pred.shape)

[190. 288. 170. 311. 118. 230. 233. 202. 179. 196.  87. 200.  43. 243.
  88. 196.  99. 279. 273. 166.  85. 141.  50. 173. 141. 178. 221.  66.
  59. 118. 200.  49. 196. 292. 220. 180.  53.  94. 120.  75.  59.]
<class 'numpy.ndarray'>
(111,)

In [ ]:
print('PREDICTED DATA',pred[:13])
print('\n\n')
print('ACTUAL DATA',y_test[:13])

PREDICTED DATA [190. 288. 170. 311. 118. 230. 233. 202. 179. 196.  87. 200.  43.]



ACTUAL DATA [219.  70. 202. 230. 111.  84. 242. 272.  94.  96.  94. 252.  99.]